/* eslint-disable sonarjs/no-duplicate-string */
export const DivisionBeats = [
  {
    num: 1,
    name: "Central",
    bureau: "Central Bureau",
  },
  {
    num: 2,
    name: "Rampart",
    bureau: "Central Bureau",
  },
  {
    num: 3,
    name: "Southwest",
    bureau: "South Bureau",
  },
  {
    num: 4,
    name: "Hollenbeck",
    bureau: "Central Bureau",
  },
  {
    num: 5,
    name: "Harbor",
    bureau: "South Bureau",
  },
  {
    num: 6,
    name: "Hollywood",
    bureau: "West Bureau",
  },
  {
    num: 7,
    name: "Wilshire",
    bureau: "West Bureau",
  },
  {
    num: 8,
    name: "West Los Angeles",
    bureau: "West Bureau",
  },
  {
    num: 9,
    name: "Van Nuys",
    bureau: "Valley Bureau",
  },
  {
    num: 10,
    name: "West Valley",
    bureau: "Valley Bureau",
  },
  {
    num: 11,
    name: "Northeast",
    bureau: "Central Bureau",
  },
  {
    num: 12,
    name: "77th Street",
    bureau: "South Bureau",
  },
  {
    num: 13,
    name: "Newton",
    bureau: "Central Bureau",
  },
  {
    num: 14,
    name: "Pacific",
    bureau: "West Bureau",
  },
  {
    num: 15,
    name: "North Hollywood",
    bureau: "Valley Bureau",
  },
  {
    num: 16,
    name: "Foothill",
    bureau: "Valley Bureau",
  },
  {
    num: 17,
    name: "Devonshire",
    bureau: "Valley Bureau",
  },
  {
    num: 18,
    name: "Southeast",
    bureau: "South Bureau",
  },
  {
    num: 19,
    name: "Mission",
    bureau: "Valley Bureau",
  },
  {
    num: 20,
    name: "Olympic",
    bureau: "Central Bureau",
  },
  {
    num: 21,
    name: "Topanga",
    bureau: "Valley Bureau",
  },
  {
    num: 22,
    name: "West Traffic",
    bureau: "Traffic Group",
  },
  {
    num: 23,
    name: "Valley Traffic",
    bureau: "Traffic Group",
  },
  {
    num: 24,
    name: "Central Traffic",
    bureau: "Traffic Group",
  },
  {
    num: 25,
    name: "South Traffic",
    bureau: "Traffic Group",
  },
  {
    num: 31,
    name: "Transit",
    bureau: "Transit Services Bureau",
  },
  {
    num: 36,
    name: "Security Services",
    bureau: "Citywide",
  },
] as const;

export const ServiceUnitTypes: ReadonlyArray<{ unit: string; desc: string }> = [
  { unit: "A", desc: "Basic two-officer patrol unit" },
  { unit: "L", desc: "Single-officer patrol unit" },
  { unit: "W", desc: "Bureau or area detective unit" },
  { unit: "K9", desc: "Police dog/canine unit" },
  { unit: "R", desc: "Metropolitan division unit" },
  { unit: "G", desc: "Gang coordinator or enforcement detail unit" },
  { unit: "S", desc: "Two-officer senior lead officer unit" },
  { unit: "SL", desc: "One-officer senior lead officer unit" },
  { unit: "E", desc: "Traffic enforcement automobile unit" },
  { unit: "M", desc: "Traffic enforcement motorcycle unit" },
  { unit: "X", desc: "Additional patrol unit in an assignment district" },
  { unit: "N", desc: "Narcotics unit" },
  { unit: "U", desc: "Report-taking unit" },
  { unit: "T", desc: "Collision investigation unit" },
  { unit: "B", desc: "Community safety partnership unit" },
  { unit: "C", desc: "Bicycle detail unit" },
  { unit: "J", desc: "Juvenile unit" },
  { unit: "F", desc: "Specialized investigative or crime task force unit" },
  { unit: "Air", desc: "Aviation patrol/support unit" },
  { unit: "BRT", desc: "Bus riding team" },
  { unit: "CP", desc: "Mobile Command post" },
  { unit: "CR", desc: "Community relations officer or unit" },
  { unit: "DV", desc: "Domestic abuse response team unit" },
  { unit: "FB", desc: "Uniformed foot-beat patrol" },
  { unit: "FM", desc: "Motor task force" },
  { unit: "FP", desc: "Fixed security post" },
  { unit: "HOPE", desc: "Homeless outreach proactive engagement unit" },
  { unit: "MQ", desc: "Specialized motorcycle unit" },
  { unit: "MV", desc: "Vice task force motorcycle unit" },
  { unit: "MX", desc: "Specialized motorcycle unit" },
  { unit: "OP", desc: "Observation post assignment unit" },
  { unit: "P", desc: "Operations bureau unit with administrative or law enforcement duties" },
  { unit: "Q", desc: "Special event or unusual occurrence unit" },
  { unit: "RP", desc: "Mobile security patrol for security services division" },
  { unit: "V", desc: "Bureau or area vice unit" },
  { unit: "VCP", desc: "Volunteer citizen patrol engagement units" },
  {
    unit: "Z",
    desc: "Uniformed unit assigned to special detail or career criminal detail",
  },
];
