name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  Label:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Label Source Changes
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/configs/Labeler.yml"

      - name: Label First Pull Request for Newcomers
        uses: actions/github-script@v7
        with:
          retries: 3
          script: |
            const Creator = context.payload.sender.login
            const { data: PullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              creator: Creator
            })

            const PreviousPRs = PullRequests.filter(pr => pr.number !== context.issue.number)
            if (PreviousPRs.length === 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['👋 - First Pull Request']
              })
            }

      - name: Assign Size Label for Modifications Made
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          xs_label: "Size - XS"
          s_label: "Size - S"
          m_label: "Size - M"
          l_label: "Size - L"
          xl_label: "Size - XL"

          message_if_xl: |-
            #### ⚠️ - Pull Request Size Exceeds Recommendation
            
            This pull request exceeds the maximum recommended size of 1,000 lines. Please consider breaking it down into smaller, focused PRs for easier review and collaboration.
