name: Code Tests & Linting
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ["main"]
    paths:
      - "Source/**"
      - "Tests/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "jest.config.*"
      - ".eslintrc.*"
      - ".prettierignore"
      - ".prettierrc.json"
  pull_request:
    branches: ["main"]
    paths:
      - "Source/**"
      - "Tests/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "jest.config.*"
      - ".eslintrc.*"
      - ".prettierignore"
      - ".prettierrc.json"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js Version 23 -  ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "23.x.x"

      - name: Use Dummy Secrets File
        run: npm run cp:secrets

      - name: Install Dependencies
        run: npm ci

      - name: Check Linting & Code Style
        run: npm run lint

      - name: Run Tests
        run: npm test -- --testPathIgnorePatterns=Secrets.*.ts
