name: Code Tests & Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js Version 21 - ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "23.x.x"

      - name: Use Dummy Secrets File
        run: npm run cp:secrets

      - name: Install App Dependencies
        run: npm ci

      - name: Check Linting & Code Style
        run: npm run lint

      - name: Run App Tests
        run: npm test -- --testPathIgnorePatterns=Secrets.*.ts
